"""add image_url to social and news

Revision ID: 8a04fcb67a09
Revises: d239b6ffffeb
Create Date: 2026-01-27 22:55:05.703394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a04fcb67a09'
down_revision = 'd239b6ffffeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('social_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_item', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.drop_column('image_url')

    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
